name: rgee smoke test
on:
  workflow_dispatch:

jobs:
  ee-init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Write EE credentials and env
        env:
          GEE_SA_KEY_B64: ${{ secrets.GEE_SA_KEY_B64 }}
          GEE_PROJECT_ID: ${{ secrets.GEE_PROJECT_ID }}
        run: |
          echo "$GEE_SA_KEY_B64" | base64 -d > $RUNNER_TEMP/ee-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/ee-key.json" >> $GITHUB_ENV
          echo "GEE_PROJECT_ID=$GEE_PROJECT_ID" >> $GITHUB_ENV

      - name: Install rgee and python deps
        run: |
          Rscript -e 'install.packages("rgee")'
          Rscript -e 'library(rgee); ee_install()'   # instala earthengine-api (conda) en el runner

      - name: Initialize rgee (non-interactive) and test
        run: |
          Rscript -e 'library(rgee); \
            ee_Initialize(auth_mode="appdefault", project=Sys.getenv("GEE_PROJECT_ID"), quiet=TRUE); \
            print(ee_user_info(quiet=TRUE)); \
            ic <- ee$ImageCollection("COPERNICUS/S2_SR")$filterDate("2024-01-01","2024-01-02"); \
            cat("ImageCollection size:", ic$size()$getInfo(), "\n"); \
            cat("✅ Earth Engine inicializado y responde.\n")'
